# Generated by Django 5.1 on 2024-08-22 14:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),  # Adjust this to match your actual last migration
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0.00),
        ),
    ]
