# Generated by Django 5.1 on 2024-08-22 14:56

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0002_rename_order_price_order_total_price_and_more'),
    ]

    operations = [
        # Remove the old order_price field
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
        # Remove the order field from OrderItem if it exists
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        # Update the order_items field to use OrderItem as the through model
        
    ]
