# Generated by Django 5.1 on 2024-08-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0003_remove_order_order_price_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
