# Generated by Django 5.1 on 2024-08-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0016_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='Story', to='foodie_app.story'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='Post', to='foodie_app.post'),
        ),
    ]
