# Generated by Django 5.1 on 2024-08-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0017_profile_stories_alter_profile_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
