# Generated by Django 5.1 on 2024-08-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0025_accommodation_restaurant_alter_order_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
