# Generated by Django 5.1 on 2024-08-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0026_remove_profile_followers_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers_number',
            field=models.ManyToManyField(blank=True, related_name='following_profiles', to='foodie_app.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower_profiles', to='foodie_app.profile'),
        ),
    ]
