# Generated by Django 5.1 on 2024-08-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0027_remove_profile_followers_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_business_owner',
            field=models.BooleanField(default=False),
        ),
    ]
